// Generated by LiveScript 1.4.0
(function(){
  var M;
  M = this.M;
  M.mod_ucat == null && (M.mod_ucat = {});
  M.mod_ucat.str = M.str.mod_ucat;
  M.mod_ucat.attempt_init = function(Y){
    this.Y = Y;
  };
  M.mod_ucat.mod_form_init = function(Y){
    var tppanel;
    this.Y = Y;
    Y = this.Y;
    Y.one('body').appendChild(Y.Node.create("<div id=\"tppanelcontent\">\n    <div class=\"yui3-widget-bd\">\n        <form id=\"targetprobabilityform\">\n            <p>" + this.str.targetprobability + "</p>\n            <p><input type=\"text\" id=\"targetprobability\"></p>\n            <div id=\"targetprobability_error\" class=\"error\"></div>\n        </form>\n    </div>\n</div>"));
    Y.one('#targetprobabilityform').on('submit', function(e){
      return e.preventDefault();
    });
    tppanel = new Y.Panel({
      modal: true,
      centered: true,
      render: true,
      visible: false,
      srcNode: '#tppanelcontent',
      width: 400,
      zIndex: 1,
      buttons: [
        {
          value: M.str.moodle.ok,
          section: Y.WidgetStdMod.FOOTER,
          action: function(e){
            var tp, logitbias, tperror;
            e.preventDefault();
            tp = parseFloat(Y.one('#targetprobability').get('value'));
            logitbias = -Math.log(tp / (1 - tp));
            tperror = Y.one('#targetprobability_error');
            tperror.setHTML == null && (tperror.setHTML = tperror.setContent);
            if (!isFinite(logitbias)) {
              tperror.setHTML(M.str.mod_ucat.tpoutofrange);
              return;
            }
            Y.one('#id_logitbias').set('value', logitbias);
            return tppanel.hide();
          }
        }, {
          value: M.str.moodle.cancel,
          section: Y.WidgetStdMod.FOOTER,
          action: function(e){
            e.preventDefault();
            return tppanel.hide();
          }
        }
      ]
    });
    return Y.one('#setlogitbiasbytp').on('click', function(){
      tppanel.show();
      return Y.one('#targetprobability').focus();
    });
  };
}).call(this);
