// Generated by LiveScript 1.4.0
(function(){
  M.block_ucat_manager == null && (M.block_ucat_manager = {
    ajaxurl: M.cfg.wwwroot + '/blocks/ucat_manager/ajax.php',
    users_init: function(Y, params){
      this.Y = Y;
      this.params = params;
      Y.one('#menuuset').on('change', function(){
        return this.ancestor('form').submit();
      });
      Y.one('#deluset').on('click', function(e){
        if (!confirm(M.str.block_ucat_manager.reallydeleteuserset)) {
          return e.preventDefault();
        }
      });
      return Y.all('.ability').on('click', function(e){
        var ability, userid, oldability, input;
        ability = e.target.getData('ability');
        userid = e.target.getData('user-id');
        oldability = ability;
        input = Y.Node.create('<input>').setAttrs({
          size: 3,
          value: ability
        });
        input.on('key', function(){
          var ability, cell;
          ability = this.get('value');
          cell = this.ancestor();
          this.set('disabled', 'disabled');
          M.util.add_spinner(Y, this.ancestor()).show();
          return Y.io(M.block_ucat_manager.ajaxurl, {
            method: 'post',
            data: {
              act: 'abilityupdate',
              course: params.course,
              uset: params.uset,
              user: userid,
              ability: ability
            },
            on: {
              success: function(id, o){
                var res;
                res = JSON.parse(o.responseText);
                cell.setData('ability', res.ability);
                return cell.setHTML(res.ability);
              },
              failure: function(id, o){
                return cell.setHTML(oldability);
              }
            }
          });
        }, 'enter');
        input.on('blur', function(){
          var cell;
          cell = this.ancestor();
          return cell.setHTML(cell.getData('ability'));
        });
        e.target.setHTML(input);
        return input.select();
      });
    }
  });
}).call(this);
